name: Gitee repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/gitee-repos-mirror.yml'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron: '*/30 20-21 * * *'  # 此处设置为北京时间 4:00、4:30、5:00、5:30 共尝试四次
  watch:
    types: [started]  # 也可以通过手动对项目 star 来触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: github/whoway
        dst: gitee/HACV
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: user
        #black_list: "mysql-server,kunpeng-mpam,hadoop,kunpengcompute.github.io,spark,spark-website,server,postgres"
        white_list: "picture,coding,command"
